In [1]:
import pandas as pd

In [2]:
import numpy as np

In [5]:
pd.options.display.max_rows = 400

In [8]:
artist = pd.read_csv('/Users/yangxi/Desktop/collecting data/collection-master/artist_data.csv',delimiter = ",", encoding ='utf_8')

In [10]:
artist = artist.rename(columns={'name':'artist'})

In [12]:
artwork = pd.read_csv('/Users/yangxi/Desktop/collecting data/collection-master/artwork_data.csv',low_memory=False, delimiter=",", encoding='utf-8')

In [14]:
DB = pd.merge(artist, artwork, on='artist')

In [15]:
DB

,id_x,artist,gender,dates,yearOfBirth,yearOfDeath,placeOfBirth,placeOfDeath,url_x,id_y,...,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url_y
0,10093,"Abakanowicz, Magdalena",Female,born 1930,1930.0,NaN,Polska,NaN,http://www.tate.org.uk/art/artists/magdalena-a...,102939,...,2009.0,Overall display dimensions variable,NaN,NaN,NaN,NaN,NaN,© Magdalena Abakanowicz,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/abakanowic...
1,10093,"Abakanowicz, Magdalena",Female,born 1930,1930.0,NaN,Polska,NaN,http://www.tate.org.uk/art/artists/magdalena-a...,102938,...,2009.0,Display dimensions: 4050 x 3820 x 4000 mm,NaN,NaN,NaN,NaN,NaN,© Magdalena Abakanowicz,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/abakanowic...
2,10093,"Abakanowicz, Magdalena",Female,born 1930,1930.0,NaN,Polska,NaN,http://www.tate.org.uk/art/artists/magdalena-a...,103642,...,2009.0,Display dimensions: 4010 x 2900 x 3700 mm,NaN,NaN,NaN,NaN,NaN,© Magdalena Abakanowicz,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/abakanowic...
3,10093,"Abakanowicz, Magdalena",Female,born 1930,1930.0,NaN,Polska,NaN,http://www.tate.org.uk/art/artists/magdalena-a...,103644,...,2009.0,"object, each: 660 x 580 x 680 mm",NaN,NaN,NaN,NaN,NaN,© Magdalena Abakanowicz,http://www.tate.org.uk/art/images/work/T/T12/T...,http://www.tate.org.uk/art/artworks/abakanowic...
4,0,"Abbey, Edwin Austin",Male,1852–1911,1852.0,1911.0,"Philadelphia, United States","London, United Kingdom",http://www.tate.org.uk/art/artists/edwin-austi...,311,...,1924.0,support: 251 x 295 mm,251,295,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/N/N03/N...,http://www.tate.org.uk/art/artworks/abbey-illu...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69308,12542,"Zorio, Gilberto",Male,born 1944,1944.0,NaN,"Andorno Micca, Italia",NaN,http://www.tate.org.uk/art/artists/gilberto-zo...,103399,...,2009.0,object: 125 x 1113 x 190 mm image: 340 x 287 m...,125,1113,190.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/zorio-hatr...
69309,2186,"Zox, Larry",Male,born 1936,1936.0,NaN,"Des Moines, United States",NaN,http://www.tate.org.uk/art/artists/larry-zox-2186,16531,...,1968.0,support: 2235 x 2489 mm,2235,2489,NaN,mm,date inscribed,"© Larry Zox, courtesy Stephen Haller Gallery, ...",http://www.tate.org.uk/art/images/work/T/T01/T...,http://www.tate.org.uk/art/artworks/zox-orange...
69310,621,"Zuccarelli, Francesco",Male,1702–1788,1702.0,1788.0,Italia,Firenze,http://www.tate.org.uk/art/artists/francesco-z...,16532,...,1985.0,support: 1264 x 1572 mm frame: 1497 x 1800 mm,1264,1572,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/T/T04/T...,http://www.tate.org.uk/art/artworks/zuccarelli...
69311,2187,"Zuloaga, Ignacio",Male,1870–1945,1870.0,1945.0,España,España,http://www.tate.org.uk/art/artists/ignacio-zul...,16533,...,1923.0,support: 292 x 406 mm frame: 470 x 585 x 93 mm,292,406,NaN,mm,NaN,"© DACS, 2014",http://www.tate.org.uk/art/images/work/N/N01/N...,http://www.tate.org.uk/art/artworks/zuloaga-vi...
69312,2188,"Zyw, Aleksander",Male,1905–1995,1905.0,1995.0,Polska,NaN,http://www.tate.org.uk/art/artists/aleksander-...,16534,...,1962.0,frame: 934 x 662 x 28 mm support: 920 x 649 mm,934,662,28.0,mm,NaN,© The estate of the Aleksander Zyw,http://www.tate.org.uk/art/images/work/T/T00/T...,http://www.tate.org.uk/art/artworks/zyw-light-...

In [19]:
median_height=DB.groupby('year')[['depth']].median().reset_index()

In [20]:
count.to_csv('DB', encoding ='utf-8',index=False)

NameError: name 'count' is not defined